import React, { useEffect, useRef, useState } from 'react'
import logo from '../assets/logo_cgpsc.png'

const STORAGE_KEY = 'cgpsc_chat_history_v1'
const CHATBOT_API_URL = (typeof window !== 'undefined' && window.__CGPSC_CHATBOT_API_URL) ? window.__CGPSC_CHATBOT_API_URL : ''

function botReplyLocal(message) {
  const q = String(message).toLowerCase()
  if (/sms/.test(q)) {
    return 'SMS generated by the system if you are not getting sms it may be cause of  DND service active or server problem.'
  }
  if (/syllabus/.test(q)) {
    return 'Please see the relevant advertisement for syllabus related query.'
  }
  if (/age relaxation|age/.test(q)) {
    return 'Please see the relevant advertisement for age related query.'
  }
  if (/ammandment|correction|mistake/.test(q)) {
    return 'If you want to correction on Candidate Name,Father Name, Mother Name or Any other correction you should email us on cgpsc.cg@gov.in with proper proof of document with support of your correction request'
  }
  if (/reservation|experience/.test(q)) {
    return 'Please see the relevant advertisement for reservation related query.'
  }
  if (/date of same|same date/.test(q)) {
    return 'You should inform to controller of exam by writting an e-mail on cgpsc.cg@gov.in and attache both exam date notificaton'
  }
  if (/date of exam|exam date/.test(q)) {
    return 'You should request to controller of exam by writting an e-mail on cgpsc.cg@gov.in and attache proper reason'
  }
  if (/carry in exam hall|exam hall/.test(q)) {
    return 'You can carry in exam hall 1 Admit Card(Hall ticket), 2.ID proof as per given in Admit card 3.good quality ball point pen, 4.transperent water bottle, 5.simple watch(not smart watch)...etc.'
  }
  if (/admit|admit card|hall ticket/.test(q)) {
    return 'Admit cards are published in the Downloads section. Search for "Admit Card" of related exam.'
  }
  if (/result|results|merit|final list/.test(q)) {
    return 'Results and merit lists are published under the Results page. Use the search box to find results by year or post.'
  }
  if (/notification|apply|application|recruitment/.test(q)) {
    return 'Notifications and recruitment details are in the Notifications and Advertisment pages. Click a notification to view full details and the application link (if open).'
  }
  if (/fee|payment/.test(q)) {
    return 'Fee payment instructions are given in the Advertised page. Typically payments are through the online portal with netbanking or card payments.'
  }
  if (/contact|office|address/.test(q)) {
    return 'Office: CGPSC Sector-19, North Block, Nava Raipur. Phone: +91-771-XXXXXXX. Email: cgpsc.cg@gov.in'
  }
  if (/hi|hello|hey|namaste/.test(q)) {
    return 'Hello! I am CGPSC Assistant — ask me about notifications, results, admit cards, or how to apply.'
  }
  if (/objection|question/.test(q)) {
    return 'You can login with your cridentials on cgpsc website and you can submit your objection..!'
  }
  if (/thanks|thank you|thanks alot/.test(q)) {
    return 'Your welcome, Have a good day..!'
  }
  return "Sorry, I don't have an exact answer for that yet. Try: 'admit card', 'result', 'notification', or 'contact'."
}

export default function Chatbot() {
  const [open, setOpen] = useState(false)
  const [history, setHistory] = useState([])
  const [input, setInput] = useState('')
  const messagesRef = useRef(null)

  useEffect(() => {
    try {
      const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]')
      setHistory(saved)
    } catch (e) { setHistory([]) }
  }, [])

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(history))
    if (messagesRef.current) {
      messagesRef.current.scrollTop = messagesRef.current.scrollHeight
    }
  }, [history])

  const addMessage = (role, text) => {
    setHistory(h => [...h, { role, text, ts: Date.now() }])
  }

  const sendToServer = async (text) => {
    if (!CHATBOT_API_URL) throw new Error('No API URL configured')
    const res = await fetch(CHATBOT_API_URL, {
      method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: text })
    })
    const data = await res.json()
    return data.reply || JSON.stringify(data)
  }

  const handleSend = async () => {
    const txt = (input || '').trim()
    if (!txt) return
    setInput('')
    addMessage('user', txt)
    addMessage('bot', 'Typing...')

    try {
      let reply
      if (CHATBOT_API_URL) {
        reply = await sendToServer(txt)
      } else {
        await new Promise(r => setTimeout(r, 400))
        reply = botReplyLocal(txt)
      }
      setHistory(h => {
        const dropped = h.slice(0, -1)
        return [...dropped, { role: 'bot', text: reply, ts: Date.now() }]
      })
    } catch (err) {
      setHistory(h => {
        const dropped = h.slice(0, -1)
        return [...dropped, { role: 'bot', text: 'Sorry, the chatbot failed to respond. Please try again later.', ts: Date.now() }]
      })
      console.error('Chatbot error', err)
    }
  }

  const handleKey = (e) => {
    if (e.key === 'Enter') {
      e.preventDefault(); handleSend()
    }
  }

  return (
    <>
      <button
        aria-label={open ? 'Close chat' : 'Open chat'}
        onClick={() => setOpen(o => !o)}
        className="fixed right-5 bottom-5 w-16 h-16 rounded-full flex items-center justify-center shadow-lg text-white z-50 bg-gradient-to-b from-cgb-500 to-cgb-700"
      >
        <svg width="26" height="26" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden>
          <path d="M21 15a2 2 0 0 1-2 2H8l-5 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v10z" fill="white" />
        </svg>
      </button>

      {open && (
        <div className="fixed right-5 bottom-24 w-96 max-w-full h-[520px] rounded-xl shadow-2xl z-40 flex flex-col bg-white">
          <div className="px-4 py-3 bg-gradient-to-r from-cgb-700 to-cgb-500 text-white flex items-center gap-3">
            <div className="flex items-center gap-3">
              <img src={logo} alt="CGPSC logo" className="w-9 h-9 rounded-xl object-contain shadow" /></div>
            <h4 className="m-0 text-sm">CGPSC Assistant</h4>
            <div className="ml-auto">
              <button onClick={() => setOpen(false)} className="text-white font-semibold">Close</button>
            </div>
          </div>

          <div ref={messagesRef} className="flex-1 overflow-auto p-3 space-y-2 bg-white">
            {history.length === 0 && (
              <div className="text-sm text-slate-500">नमस्ते! CGPSC Assistant में आपका स्वागत है। Try: \"admit card\", \"result\", \"correction\", or \"notification\"</div>
            )}
            {history.map((m, idx) => (
              <div key={idx} className={m.role === 'user' ? 'flex justify-end' : 'flex justify-start'}>
                <div className={m.role === 'user' ? 'max-w-[85%] bg-gradient-to-b from-cgb-500 to-cgb-700 text-white p-3 rounded-lg' : 'max-w-[85%] bg-slate-100 border p-3 rounded-lg text-slate-800'}>
                  {m.text}
                </div>
              </div>
            ))}
          </div>

          <div className="p-3 border-t flex gap-2">
            <input
              value={input}
              onChange={e => setInput(e.target.value)}
              onKeyDown={handleKey}
              placeholder="Ask about notifications, results, admit card..."
              className="flex-1 border rounded-md px-3 py-2"
            />
            <button onClick={handleSend} className="bg-cgb-500 text-white px-3 py-2 rounded-md">Send</button>
          </div>
        </div>
      )}
    </>
  )
}
